#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ksiazki")]
	public partial class KsiazkiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKsiazki(Ksiazki instance);
    partial void UpdateKsiazki(Ksiazki instance);
    partial void DeleteKsiazki(Ksiazki instance);
    #endregion
		
		public KsiazkiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["KsiazkiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KsiazkiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KsiazkiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KsiazkiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KsiazkiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ksiazki> Ksiazkis
		{
			get
			{
				return this.GetTable<Ksiazki>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ksiazki")]
	public partial class Ksiazki : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Tytul;
		
		private string _Autor;
		
		private int _Rwydania;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTytulChanging(string value);
    partial void OnTytulChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnRwydaniaChanging(int value);
    partial void OnRwydaniaChanged();
    #endregion
		
		public Ksiazki()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tytul", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tytul
		{
			get
			{
				return this._Tytul;
			}
			set
			{
				if ((this._Tytul != value))
				{
					this.OnTytulChanging(value);
					this.SendPropertyChanging();
					this._Tytul = value;
					this.SendPropertyChanged("Tytul");
					this.OnTytulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autor", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Autor
		{
			get
			{
				return this._Autor;
			}
			set
			{
				if ((this._Autor != value))
				{
					this.OnAutorChanging(value);
					this.SendPropertyChanging();
					this._Autor = value;
					this.SendPropertyChanged("Autor");
					this.OnAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rwydania", DbType="Int NOT NULL")]
		public int Rwydania
		{
			get
			{
				return this._Rwydania;
			}
			set
			{
				if ((this._Rwydania != value))
				{
					this.OnRwydaniaChanging(value);
					this.SendPropertyChanging();
					this._Rwydania = value;
					this.SendPropertyChanged("Rwydania");
					this.OnRwydaniaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
