<?xml version="1.0" encoding="utf-8"?><Database Name="Studenci" Class="StudenciDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=Studenci;Integrated Security=True" SettingsObjectName="_2._5._3.Properties.Settings" SettingsPropertyName="StudenciConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Imie" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DataUr" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Miasto" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Miejscowosc_Student" Member="Miejscowosc" ThisKey="Miasto" OtherKey="Nazwa" Type="Miejscowosc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Miejscowosc" Member="Miejscowoscs">
    <Type Name="Miejscowosc">
      <Column Name="Nazwa" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Miejscowosc_Student" Member="Students" ThisKey="Nazwa" OtherKey="Miasto" Type="Student" />
    </Type>
  </Table>
</Database>